/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import static java.awt.Color.red;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author Romildo A. Lima Jr.
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        getContentPane().setBackground(red);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        barraLateral = new javax.swing.JInternalFrame();
        jlbData = new javax.swing.JLabel();
        jlbHora = new javax.swing.JLabel();
        jlbDia = new javax.swing.JLabel();
        telaInterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadCarro = new javax.swing.JMenuItem();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuCadProdutos = new javax.swing.JMenuItem();
        menuCadUsuario = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuConFuncionario = new javax.swing.JMenuItem();
        menuConVeiculo = new javax.swing.JMenuItem();
        menuBalcao = new javax.swing.JMenu();
        menuBalcCaixa = new javax.swing.JMenuItem();
        menuBalPreco = new javax.swing.JMenuItem();
        menuBalProduto = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuRelOs = new javax.swing.JMenuItem();
        menuRelVendas = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina Quebra Tudo");
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        barraLateral.setVisible(true);

        jlbData.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jlbData.setForeground(new java.awt.Color(204, 0, 0));
        jlbData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbData.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jlbData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlbHora.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jlbHora.setForeground(new java.awt.Color(204, 0, 0));
        jlbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbHora.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jlbHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jlbDia.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jlbDia.setForeground(new java.awt.Color(204, 0, 0));
        jlbDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDia.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jlbDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral.getContentPane());
        barraLateral.getContentPane().setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbDia, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jlbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout telaInternaLayout = new javax.swing.GroupLayout(telaInterna);
        telaInterna.setLayout(telaInternaLayout);
        telaInternaLayout.setHorizontalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        telaInternaLayout.setVerticalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCadastro.png"))); // NOI18N
        menuCadastro.setText("Cadastro");

        menuCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeVeiculo.png"))); // NOI18N
        menuCadCarro.setText("Carros");
        menuCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCarroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadCarro);

        menuCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconePessoas.png"))); // NOI18N
        menuCadFuncionario.setText("Funcionário");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadFuncionario);

        menuCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeProd.png"))); // NOI18N
        menuCadProdutos.setText("Produtos");
        menuCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutosActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadProdutos);

        menuCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeUsuario (2).png"))); // NOI18N
        menuCadUsuario.setText("Usuário");
        menuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadUsuario);

        jMenuBar1.add(menuCadastro);

        menuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeConsulta.png"))); // NOI18N
        menuConsulta.setText("Consulta");

        menuConFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeBuscPessoa.png"))); // NOI18N
        menuConFuncionario.setText("Funcionário");
        menuConsulta.add(menuConFuncionario);

        menuConVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeBuscarCarro.png"))); // NOI18N
        menuConVeiculo.setText("Veículos");
        menuConsulta.add(menuConVeiculo);

        jMenuBar1.add(menuConsulta);

        menuBalcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeBalcao.png"))); // NOI18N
        menuBalcao.setText("Balcão");

        menuBalcCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCaixa (2).png"))); // NOI18N
        menuBalcCaixa.setText("Caixa");
        menuBalcao.add(menuBalcCaixa);

        menuBalPreco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCaixa.png"))); // NOI18N
        menuBalPreco.setText("Preço");
        menuBalcao.add(menuBalPreco);

        menuBalProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCaixaProd.png"))); // NOI18N
        menuBalProduto.setText("Produto");
        menuBalcao.add(menuBalProduto);

        jMenuBar1.add(menuBalcao);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeRel.png"))); // NOI18N
        menuRelatorio.setText("Relatórios");

        menuRelOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeRelOS.png"))); // NOI18N
        menuRelOs.setText("Ordem de Serviço");
        menuRelatorio.add(menuRelOs);

        menuRelVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeRelVenda.png"))); // NOI18N
        menuRelVendas.setText("Vendas");
        menuRelatorio.add(menuRelVendas);

        jMenuBar1.add(menuRelatorio);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeHelp.png"))); // NOI18N
        menuAjuda.setText("Ajuda");
        jMenuBar1.add(menuAjuda);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeSair.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaInterna))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateral)
            .addComponent(telaInterna)
        );

        setSize(new java.awt.Dimension(816, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
        
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
        Date dataAtual = new Date();
        jlbData.setText(formatar.format(dataAtual));
        
        SimpleDateFormat formatarHora = new SimpleDateFormat("HH:mm:ss");
        Date horaAtual = new Date();
        jlbHora.setText(formatarHora.format(horaAtual));
        
        SimpleDateFormat formatarDia = new SimpleDateFormat("F");
        Date diaAtual = new Date();
        String dia = formatarDia.format(diaAtual);
        
        switch (dia){
            case "1":
                jlbDia.setText("Domingo");
                break;
            case "2":
                jlbDia.setText("Segunda-feira");
                break;
            case "3":
                jlbDia.setText("Terça-feira");
                break;
            case "4":
                jlbDia.setText("Quarta-feira");
                break;
            case "5":
                jlbDia.setText("Quinta-feira");
                break;
            case "6":
                jlbDia.setText("Sexta-feira");
                break;
            case "7":
                jlbDia.setText("Sábado");
                break;   
        }       
    }//GEN-LAST:event_formWindowOpened

    private void menuCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCarroActionPerformed
        // Chamar a tela de veículos
        TelaVeiculos veiculos = new TelaVeiculos();
        telaInterna.add(veiculos);
        veiculos.setVisible(true);
       
    }//GEN-LAST:event_menuCadCarroActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed
        // Chamar a tela de funcionários
        TelaFuncionarios funcionarios = new TelaFuncionarios();
        telaInterna.add(funcionarios);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutosActionPerformed
        // Chamar a tela de Produtos
        TelaProdutos produtos = new TelaProdutos();
        telaInterna.add(produtos);
        produtos.setVisible(true);
        
    }//GEN-LAST:event_menuCadProdutosActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:]
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadUsuarioActionPerformed
        // TODO add your handling code here:
        TelaUsuario usuario = new TelaUsuario();
        telaInterna.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_menuCadUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Liquid".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame barraLateral;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbDia;
    private javax.swing.JLabel jlbHora;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuBalPreco;
    private javax.swing.JMenuItem menuBalProduto;
    private javax.swing.JMenuItem menuBalcCaixa;
    private javax.swing.JMenu menuBalcao;
    private javax.swing.JMenuItem menuCadCarro;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuCadProdutos;
    private javax.swing.JMenuItem menuCadUsuario;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuConFuncionario;
    private javax.swing.JMenuItem menuConVeiculo;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuRelOs;
    private javax.swing.JMenuItem menuRelVendas;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JDesktopPane telaInterna;
    // End of variables declaration//GEN-END:variables

}

